options:
    merge-default-rules: false
files:
    include: 'src/**/*.s+(a|c)ss'
rules:
    one-declaration-per-line: 2
    empty-line-between-blocks: 0
    single-line-per-selector: 2
    attribute-quotes: 2
    border-zero:
        - 2
        - convention: 'none'
    brace-style:
        - 2
        - style: 'stroustrup'
        - allow-single-line: false
    declarations-before-nesting: 2
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline: 2
    force-element-nesting: 1
    force-pseudo-nesting: 1
    function-name-format:
        - 2
        - convention: 'camelcase'
    hex-length:
        - 2
        - style: 'long'
    hex-notation:
        - 2
        - style: 'lowercase'
    indentation:
        - 2
        - size: 'tab'
    leading-zero:
        - 2
        - include: true
    no-color-keywords: 2
    no-duplicate-properties: 2
    no-empty-rulesets: 2
    no-invalid-hex: 2
    no-misspelled-properties: 2
    no-trailing-whitespace: 2
    no-transition-all: 2
    quotes:
        - 2
        - style: 'double'
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator: 2
    space-before-bang: 2
    space-before-brace: 2
    space-before-colon: 2
    space-between-parens: 2
    trailing-semicolon: 2
    url-quotes: 2
    zero-unit: 2
